### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by chrisrjohnson** [chrisrjohnson/RiffReader-Issues#1]
Summary:
Device:
Device OS:
Device Screen Size:
Device Resolution:
Browser:
Browser Version:
Screenshot:
Other Additional Info:

---

Summary: (Example #1) Can't open the "About" page.
Device: iPad 3
Device OS: OSX 6
Device Resolution: 2048 x 1536
Browser: Safari
Browser Version: 5.1
Screenshot URL: (A full URL here to an image)
Other Additional Info: None

**Comment by AdrianaLuca** [comment]
Closing issue so it won't interfere with valid issues count.
