### ISSUE TITLE
Error message when searching friends

### ISSUE THREAD

**Issue by AdrianaLuca** [chrisrjohnson/RiffReader-Issues#3]
Summary: Error message when searching friends
Device:PC
Device Resolution:1280*800
Browser:Google Chrome
Browser Version: 42.0.2311.90
Screenshot:
![error message on search friends](https://cloud.githubusercontent.com/assets/11813197/7274135/e45f6714-e902-11e4-83d8-374c7cb5ad97.JPG)

URL: https://riffreader.com/Misc/Error

**Steps to reproduce:**
1. Log in to the riffreader.rom.
2. Click on Profile.
3. Click on Find friends.
4. On Search by name, write one or two letters (eg. "a", "ba").
5. Click Search.

**Actual result:**
An error message is shown.

**Expected result:** 
"Member search results" and "No members found" should be shown.

**Comment by chrisrjohnson** [comment]
Fixed. Please verify.

**Comment by AdrianaLuca** [comment]
Verified fixed. When searching with only two characters, a message is shown "Search query is invalid. Minimum of 3 characters.". 3 or more characters search finds friends.
