### ISSUE TITLE
Story 144182 and 144140 contain (min-width : 500px) {.ethanmobile

### ISSUE THREAD

**Issue by AdrianaLuca** [chrisrjohnson/RiffReader-Issues#9]
Summary: Story 144182 and 144140 contain code
Device: PC, Mac, iPad
Device Resolution:1280*800
Browser: All tested (Mac: FF, Chrome, Safari; WinXP: Chrome; iPad: Chrome, Safari)
Screenshot URL: 
![code](https://cloud.githubusercontent.com/assets/11813197/7281345/b89f554c-e931-11e4-93da-7abd2cd9824b.png)

Steps to reproduce:
1. Open:
https://riffreader.com/pageitem/144182
https://riffreader.com/pageitem/144140

Actual result:
Code characters are displayed: (min-width : 500px) {.ethanmobile { display: none; }}

Expected result:
No code should be displayed.

**Comment by chrisrjohnson** [comment]
Fixed.

**Comment by AdrianaLuca** [comment]
Verified fixed, the issue no longer reproduced.
